name: Live Elements Js Compiler Build Matrix

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-18.04]
        include:
        - os: macos-latest
          NAME: macos
          TARGET: x86_64-apple-darwin
          COMPILER: clang
          LINKER: clang
        - os: ubuntu-18.04
          NAME: ubuntu
          TARGET: x86_64-linux
          COMPILER: g++
          LINKER: g++
        - os: windows-latest
          NAME: windows
          platform: win32
          arch: x64

    steps:
      - uses: actions/checkout@v1

      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Get Archive Name
        id: get_archive_name
        run: echo "::set-output name=ARCHIVE_FILENAME::live-elements-js-compiler"

      - name: Use Archive Test
        run: echo $ARCHIVE_NAME
        env:
          ARCHIVE_NAME: ${{ steps.get_archive_name.outputs.ARCHIVE_FILENAME }}

